hip_joint_position_controller:
  # type: position_controllers/JointPositionController
  type: effort_controllers/JointEffortController
  joint: "hip_joint"
  pid: {p: 100.0, i: 0.01, d: 10.0}

# hip_joint_position_controller:
#   type: position_controllers/JointPositionController
#   # type: effort_controllers/JointEffortController
#   joint: "hip_joint"
#   pid: {p: 100.0, i: 0.01, d: 10.0}


joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 150

# gazebo_ros_control:
#   pid_gains:
#     hip_joint:
#       p: 100.0
#       i: 0.01
#       d: 10.0

#  Namespace: /mugatu_urdf/gazebo_ros_control/pid_gains/hip_joint